### ISSUE TITLE
Message priority

### ISSUE THREAD

**Issue by Zomis** [Zomis/Duga#121]
Let's say that there are 20 messages queued up, then if bot is told to post a message with higher priority, then that message should skip ahead of messages with lower priority so that it is posted earlier.

**Comment by jacwah** [comment]
I looked through the code and came up with a potential solution, please tell me what you think!

The natural solution in my mind is to use a priority queue instead of a linear queue in `StackExchangeChatBot`. Messages can have a new field called `priority` with an enum type and either implement `Comparable` or use a `Comparator`.

In this way Duga can support a range of priorities and let a standard library data structure handle the implementation.

**Comment by Zomis** [comment]
@jacwah Yes, a priority queue could be a solution. But I am sometimes considering if the messages should be sortable *after* being inserted into the queue. Say that I would want @DugaBot to suddenly prioritize a specific kind of message? (Although this might be a "YAGNI")

**Comment by jacwah** [comment]
> But I am sometimes considering if the messages should be sortable after being inserted into the queue.

What use cases are you considering? Anyway, couldn't this be achieved by using a custom Comparator? Or is the order set after inserting an element?

**Comment by Zomis** [comment]
This is not needed. Closing this.
