### ISSUE TITLE
Support status events

### ISSUE THREAD

**Issue by skiwi2** [Zomis/Duga#31]
Status events should be added, even though the bot will not use it, others may want to use it.

**Comment by Zomis** [comment]
I'm not quite sure what [status events](https://developer.github.com/v3/activity/events/types/#statusevent) are, or how often they would be used. It would probably be quite easy to add this, but would it ever be used?

**Comment by Zomis** [comment]
It seems like status events can be used as a replacement for the Travis CI and AppVeyor webhooks. This should be investigated more.

**Comment by Vogel612** [comment]
At least travis sends a "Pending" status. It might be preferrable to just Acknowledge and then drop that status, since it adds no helpful information.

I don't know how AppVeyor works with that, but IIUC these two will work with the same kind of status. 
A travis payload can be seen [here](http://pastie.org/private/suarowulersviiwer9ojq)
