### ISSUE TITLE
Limit the length of Comments posted to chat

### ISSUE THREAD

**Issue by ckuhn203** [Zomis/Duga#75]
Consider this message posted to the Code Review VBA chat room.

http://chat.stackexchange.com/transcript/message/20662272#20662272

The Issue submitted on GitHub contained  a stack trace, so when Duga picked it up and posted it to chat, it pretty much just stopped chat dead. I had to scroll several screens to get to the end of the post. It would be nice to limit the number of comments that can be posted from a single hook event. Perhaps two or three at the most? The service posts links to the GitHub item, so I think it's okay to truncate the message when it's very long.

**Comment by Zomis** [comment]
Holy crap that's a long one. Indeed, this is a good suggestion, shouldn't be too hard to fix.

**Comment by Vogel612** [comment]
Even short events already Take two messages, since the link line is one message and the quoted part another. It happens quite often that a third message is neeeded if e.g. an issue description requires more than 500 characters.

These 500 chars are the upper limit of a messages length if it's not a codeblock.

Codeblocks would get collapsed though. Could it be a more favorable solution to post github code as a separate Collapsible message?

**Comment by Zomis** [comment]
I thought I had fixed this already but apparently I haven't.

**Comment by ckuhn203** [comment]
This appears to have completed now.
